return {
   { actor = "Airis" },
   "We're not a military organization, though.",
   "Or even have as much leverage as a school bake sale.",
   { actor = "Zena" },
   "...Well, no. No, we most certainly do not, @iAiris@r.",
   "That's why I'm thinking we should expand our propaganda operations.",
   "Like those weird cult organizations touting that the world will turn into swiss cheese in three months.",
   "I've been researching a lot of that stuff recently.",
   { actor = "Airis" },
   "Ooh, sounds fun!",
   { actor = "Zena" },
   "Most certainly.",
   "Have @iyou@r heard of them?",
   "Apparently it's a rather common practice in some countries to set up weird organizations that are merely a front for more important business matters.",
   "That's just what we need.",
   "First we'll need to find a vacant property somewhere in the city. The one you left behind from the previous \"transfer of ownership\" operation should do.",
   "Then, we can set up a base of operation there, to attract interested parties. You know, preaching to the masses about catastrophe this or apocalypse that.",
   "This should get them interested in the idea of \"whole planet migration\".",
   { actor = "Airis" },
   "It's gonna be a party!",
   { actor = "Zena" },
   "Apparently, the way to set this up on Earth is to go into a @c{0,255,0}[Real Estate Office]@r and buy a permit for the desired building.",
   "Then you find a vacant lot somewhere and @b[Use]@r it there, and she's all yours.",
   "Each lot has a specific size, like @b[S]@r, @b[M]@r or @b[L]@r, and only a permit that matches the size of the lot can be used. Be sure to pay attention.",
   "We'll also need a confidant to staff the building. You @iare@r making friends, aren't you?",
   "Let's commence the operation."
}
